### ISSUE TITLE
Turn Twitter impression counts into old-school view countersが動かなくなりました

### ISSUE THREAD

**Issue by kingtosh** [puhitaku/aburazaru#2]
Turn Twitter impression counts into old-school view countersが動かなくなりました。
x.comを「ユーザーによる include」に追加してももうダメなようです。
お手隙の時にでも対応していただけると幸いです。

愛用しておりましたので、動かないと寂しいです。

**Comment by puhitaku** [comment]
報告ありがとうございます、 https://github.com/puhitaku/aburazaru/commit/6dc898da34416b38cd9402fa498c978a59ad27a0 にてドメイン指定を変更し動作することを確認しました
